# Generated by Django 5.2.7 on 2025-10-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillaven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('preview_image', models.ImageField(upload_to='projects_images/')),
                ('website_image', models.ImageField(upload_to='projects_images/')),
                ('tagline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.CharField(max_length=500)),
                ('linkedin_url', models.CharField(max_length=500)),
                ('instagram_url', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
