# Generated by Django 5.2.7 on 2025-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillaven', '0002_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
